### ISSUE TITLE
FREE-SCADA ROADMAP (2024)

### ISSUE THREAD

**Issue by jakkunight** [israelpaniaguadev/free-scada#14]
Here's a roadmap of what we plan to do in 2024:

- [ ] Create the Serializer/Deserializer module. (in progress)
- [ ] Create the TCP/IP backend server for the "Local" SCADA module.
- [ ] Support generic device models.
- [ ] Create the basic Database schema for generic Device models.
- [ ] Create the native/web-based UI for the "Local" SCADA module.

Any modifications are welcome. Please open an issue if you have some suggestions for the project which are not listed in this roadmap.

The roadmap has priority over everything else. If you think that something must be part of the roadmap, feel free to post it on this issue.
